// Generated by scripts/importDice20.py.
export const DICE_20_CANVAS = { width: 1440, height: 3120 } as const;
export const DICE_20_LANDING_RECT = { x: 547, y: 1720, width: 319, height: 280 } as const;
export const DICE_20_RESULTS = [
  require("../../assets/ported/game/dice20/roll-01.png"),
  require("../../assets/ported/game/dice20/roll-02.png"),
  require("../../assets/ported/game/dice20/roll-03.png"),
  require("../../assets/ported/game/dice20/roll-04.png"),
  require("../../assets/ported/game/dice20/roll-05.png"),
  require("../../assets/ported/game/dice20/roll-06.png"),
  require("../../assets/ported/game/dice20/roll-07.png"),
  require("../../assets/ported/game/dice20/roll-08.png"),
  require("../../assets/ported/game/dice20/roll-09.png"),
  require("../../assets/ported/game/dice20/roll-10.png"),
  require("../../assets/ported/game/dice20/roll-11.png"),
  require("../../assets/ported/game/dice20/roll-12.png"),
  require("../../assets/ported/game/dice20/roll-13.png"),
  require("../../assets/ported/game/dice20/roll-14.png"),
  require("../../assets/ported/game/dice20/roll-15.png"),
  require("../../assets/ported/game/dice20/roll-16.png"),
  require("../../assets/ported/game/dice20/roll-17.png"),
  require("../../assets/ported/game/dice20/roll-18.png"),
  require("../../assets/ported/game/dice20/roll-19.png"),
  require("../../assets/ported/game/dice20/roll-20.png")
] as const;
