// Generated by scripts/importInventoryEquipment12.py.
export const INVENTORY_EQUIPMENT_12_CANVAS = { width: 1440, height: 3120 } as const;
export const INVENTORY_BOARD = { source: require("../../assets/ported/menu/inventoryEquipment12/ELD-IE12-Inventory.png"), rect: { x: 20, y: 6, width: 1382, height: 2603 } } as const;
export const EQUIPMENT_BOARD = { source: require("../../assets/ported/menu/inventoryEquipment12/ELD-IE12-Equipment.png"), rect: { x: 147, y: 433, width: 1019, height: 2405 } } as const;
