import type { ArtworkLayer } from './layerAssets';

export const TAVERN_UPSTAIRS_CONSISTENCY_SOURCE_IDS = new Set([
  'ELD-ENC-TU-001',
  'ELD-ENC-TU-002',
  'ELD-ENC-TU-003',
  'ELD-ENC-TU-004',
  'ELD-ENC-TU-005',
  'ELD-ENC-TU-006',
  'ELD-ENC-TU-007',
  'ELD-ENC-TU-008',
  'ELD-ENC-TU-009',
  'ELD-ENC-TU-010',
  'ELD-ENC-TU-011',
  'ELD-ENC-TU-012',
  'ELD-ENC-TU-013',
  'ELD-ENC-TU-014',
  'ELD-ENC-TU-015',
  'ELD-ENC-TU-016',
  'ELD-ENC-TU-017',
  'ELD-ENC-TU-018',
  'ELD-ENC-TU-020',
  'ELD-ENC-TU-021',
  'ELD-ENC-TU-022',
  'ELD-ENC-TU-023',
  'ELD-ENC-TU-024',
  'ELD-ENC-TU-025',
  'ELD-ENC-TU-026',
  'ELD-ENC-TU-027',
  'ELD-ENC-TU-028',
  'ELD-ENC-TU-029',
  'ELD-ENC-TU-030',
  'ELD-ENC-TU-031',
  'ELD-ENC-TU-032',
  'ELD-ENC-TU-033',
  'ELD-ENC-TU-034',
  'ELD-ENC-TU-035',
  'ELD-ENC-TU-036',
  'ELD-ENC-TU-037',
  'ELD-ENC-TU-038',
  'ELD-ENC-TU-039',
  'ELD-ENC-TU-040',
  'ELD-ENC-TU-041',
  'ELD-ENC-TU-042',
  'ELD-ENC-TU-044',
]);

export const TAVERN_UPSTAIRS_CONSISTENCY_LAYERS: ArtworkLayer[] = [
  {...{"id":"ELD-ENC-TU-045","displayName":"Layer 9 - Consistency Outline","hidden":false,"opacity":1.0,"order":0,"rect":{"x":615,"y":1022,"width":318,"height":519}},source:require("../../assets/ported/layers/tavernUpstairs/Derived/Consistency/ELD-ENC-TU-001_layer_9_outlined.png")},
  {...{"id":"ELD-ENC-TU-046","displayName":"Layer 9 - Consistency Outline","hidden":false,"opacity":0.0012401429703459144,"order":1,"rect":{"x":623,"y":1016,"width":316,"height":535}},source:require("../../assets/ported/layers/tavernUpstairs/Derived/Consistency/ELD-ENC-TU-002_layer_9_outlined.png")},
  {...{"id":"ELD-ENC-TU-047","displayName":"Layer 10 - Consistency Outline","hidden":false,"opacity":1.0,"order":2,"rect":{"x":731,"y":1483,"width":178,"height":66}},source:require("../../assets/ported/layers/tavernUpstairs/Derived/Consistency/ELD-ENC-TU-003_layer_10_outlined.png")},
  {...{"id":"ELD-ENC-TU-048","displayName":"Human + Huntsman - Consistency Outline","hidden":false,"opacity":1.0,"order":3,"rect":{"x":418,"y":196,"width":372,"height":46}},source:require("../../assets/ported/layers/tavernUpstairs/Derived/Consistency/ELD-ENC-TU-004_human_huntsman_outlined.png")},
  {...{"id":"ELD-ENC-TU-049","displayName":"Karl - Consistency Outline","hidden":false,"opacity":1.0,"order":4,"rect":{"x":418,"y":107,"width":174,"height":82}},source:require("../../assets/ported/layers/tavernUpstairs/Derived/Consistency/ELD-ENC-TU-005_karl_outlined.png")},
  {...{"id":"ELD-ENC-TU-050","displayName":"Lvl 2 - Consistency Outline","hidden":false,"opacity":1.0,"order":5,"rect":{"x":418,"y":271,"width":110,"height":50}},source:require("../../assets/ported/layers/tavernUpstairs/Derived/Consistency/ELD-ENC-TU-006_lvl_2_outlined.png")},
  {...{"id":"ELD-ENC-TU-051","displayName":"XP  0/500 - Consistency Outline","hidden":false,"opacity":1.0,"order":6,"rect":{"x":766,"y":327,"width":182,"height":49}},source:require("../../assets/ported/layers/tavernUpstairs/Derived/Consistency/ELD-ENC-TU-007_xp_0_500_outlined.png")},
  {...{"id":"ELD-ENC-TU-052","displayName":"HP 20 - Consistency Outline","hidden":false,"opacity":1.0,"order":7,"rect":{"x":1064,"y":221,"width":250,"height":78}},source:require("../../assets/ported/layers/tavernUpstairs/Derived/Consistency/ELD-ENC-TU-008_hp_20_outlined.png")},
  {...{"id":"ELD-ENC-TU-053","displayName":"Layer 29 - Consistency Outline","hidden":false,"opacity":1.0,"order":8,"rect":{"x":146,"y":1824,"width":1148,"height":412}},source:require("../../assets/ported/layers/tavernUpstairs/Derived/Consistency/ELD-ENC-TU-009_layer_29_outlined.png")},
  {...{"id":"ELD-ENC-TU-054","displayName":"Inserted Image - Consistency Outline","hidden":false,"opacity":1.0,"order":9,"rect":{"x":979,"y":75,"width":393,"height":370}},source:require("../../assets/ported/layers/tavernUpstairs/Derived/Consistency/ELD-ENC-TU-010_inserted_image_outlined.png")},
  {...{"id":"ELD-ENC-TU-055","displayName":"Layer 19 - Consistency Outline","hidden":false,"opacity":1.0,"order":10,"rect":{"x":88,"y":104,"width":295,"height":302}},source:require("../../assets/ported/layers/tavernUpstairs/Derived/Consistency/ELD-ENC-TU-011_layer_19_outlined.png")},
  {...{"id":"ELD-ENC-TU-056","displayName":"Layer 17 - Consistency Outline","hidden":false,"opacity":1.0,"order":11,"rect":{"x":66,"y":90,"width":350,"height":323}},source:require("../../assets/ported/layers/tavernUpstairs/Derived/Consistency/ELD-ENC-TU-012_layer_17_outlined.png")},
  {...{"id":"ELD-ENC-TU-057","displayName":"Layer 17 - Consistency Outline","hidden":false,"opacity":1.0,"order":12,"rect":{"x":54,"y":79,"width":373,"height":345}},source:require("../../assets/ported/layers/tavernUpstairs/Derived/Consistency/ELD-ENC-TU-013_layer_17_outlined.png")},
  {...{"id":"ELD-ENC-TU-058","displayName":"Layer 21 - Consistency Outline","hidden":false,"opacity":0.7732076644897461,"order":13,"rect":{"x":402,"y":283,"width":375,"height":134}},source:require("../../assets/ported/layers/tavernUpstairs/Derived/Consistency/ELD-ENC-TU-014_layer_21_outlined.png")},
  {...{"id":"ELD-ENC-TU-059","displayName":"Layer 15 - Consistency Outline","hidden":false,"opacity":1.0,"order":14,"rect":{"x":1,"y":24,"width":1449,"height":2630}},source:require("../../assets/ported/layers/tavernUpstairs/Derived/Consistency/ELD-ENC-TU-015_layer_15_outlined.png")},
  {...{"id":"ELD-ENC-TU-060","displayName":"Layer 13 - Consistency Outline","hidden":false,"opacity":1.0,"order":15,"rect":{"x":61,"y":2126,"width":1319,"height":418}},source:require("../../assets/ported/layers/tavernUpstairs/Derived/Consistency/ELD-ENC-TU-016_layer_13_outlined.png")},
  {...{"id":"ELD-ENC-TU-061","displayName":"Layer 27 - Consistency Outline","hidden":false,"opacity":1.0,"order":16,"rect":{"x":87,"y":2293,"width":1258,"height":765}},source:require("../../assets/ported/layers/tavernUpstairs/Derived/Consistency/ELD-ENC-TU-017_layer_27_outlined.png")},
  {...{"id":"ELD-ENC-TU-062","displayName":"Layer 3 - Consistency Outline","hidden":false,"opacity":1.0,"order":17,"rect":{"x":-5,"y":442,"width":1450,"height":2556}},source:require("../../assets/ported/layers/tavernUpstairs/Derived/Consistency/ELD-ENC-TU-018_layer_3_outlined.png")},
  {...{"id":"ELD-ENC-TU-063","displayName":"Layer 42 - Consistency Outline","hidden":false,"opacity":1.0,"order":19,"rect":{"x":-10,"y":478,"width":1409,"height":1108}},source:require("../../assets/ported/layers/tavernUpstairs/Derived/Consistency/ELD-ENC-TU-020_layer_42_outlined.png")},
  {...{"id":"ELD-ENC-TU-064","displayName":"Inserted Image - Consistency Outline","hidden":false,"opacity":1.0,"order":20,"rect":{"x":18,"y":475,"width":1411,"height":1223}},source:require("../../assets/ported/layers/tavernUpstairs/Derived/Consistency/ELD-ENC-TU-021_inserted_image_outlined.png")},
  {...{"id":"ELD-ENC-TU-065","displayName":"Layer 48 - Consistency Outline","hidden":false,"opacity":1.0,"order":21,"rect":{"x":17,"y":1060,"width":600,"height":575}},source:require("../../assets/ported/layers/tavernUpstairs/Derived/Consistency/ELD-ENC-TU-022_layer_48_outlined.png")},
  {...{"id":"ELD-ENC-TU-066","displayName":"Inserted Image - Consistency Outline","hidden":false,"opacity":1.0,"order":22,"rect":{"x":340,"y":826,"width":985,"height":700}},source:require("../../assets/ported/layers/tavernUpstairs/Derived/Consistency/ELD-ENC-TU-023_inserted_image_outlined.png")},
  {...{"id":"ELD-ENC-TU-067","displayName":"Layer 44 - Consistency Outline","hidden":false,"opacity":1.0,"order":23,"rect":{"x":21,"y":454,"width":1362,"height":999}},source:require("../../assets/ported/layers/tavernUpstairs/Derived/Consistency/ELD-ENC-TU-024_layer_44_outlined.png")},
  {...{"id":"ELD-ENC-TU-068","displayName":"Inserted Image - Consistency Outline","hidden":false,"opacity":1.0,"order":24,"rect":{"x":43,"y":813,"width":1407,"height":1069}},source:require("../../assets/ported/layers/tavernUpstairs/Derived/Consistency/ELD-ENC-TU-025_inserted_image_outlined.png")},
  {...{"id":"ELD-ENC-TU-069","displayName":"Inserted Image - Consistency Outline","hidden":false,"opacity":1.0,"order":25,"rect":{"x":12,"y":887,"width":353,"height":560}},source:require("../../assets/ported/layers/tavernUpstairs/Derived/Consistency/ELD-ENC-TU-026_inserted_image_outlined.png")},
  {...{"id":"ELD-ENC-TU-070","displayName":"Layer 60 - Consistency Outline","hidden":false,"opacity":1.0,"order":26,"rect":{"x":525,"y":825,"width":526,"height":320}},source:require("../../assets/ported/layers/tavernUpstairs/Derived/Consistency/ELD-ENC-TU-027_layer_60_outlined.png")},
  {...{"id":"ELD-ENC-TU-071","displayName":"Inserted Image - Consistency Outline","hidden":false,"opacity":1.0,"order":27,"rect":{"x":202,"y":1523,"width":174,"height":214}},source:require("../../assets/ported/layers/tavernUpstairs/Derived/Consistency/ELD-ENC-TU-028_inserted_image_outlined.png")},
  {...{"id":"ELD-ENC-TU-072","displayName":"Inserted Image - Consistency Outline","hidden":false,"opacity":1.0,"order":28,"rect":{"x":207,"y":886,"width":291,"height":768}},source:require("../../assets/ported/layers/tavernUpstairs/Derived/Consistency/ELD-ENC-TU-029_inserted_image_outlined.png")},
  {...{"id":"ELD-ENC-TU-073","displayName":"Inserted Image - Consistency Outline","hidden":false,"opacity":1.0,"order":29,"rect":{"x":203,"y":789,"width":316,"height":871}},source:require("../../assets/ported/layers/tavernUpstairs/Derived/Consistency/ELD-ENC-TU-030_inserted_image_outlined.png")},
  {...{"id":"ELD-ENC-TU-074","displayName":"Inserted Image - Consistency Outline","hidden":false,"opacity":1.0,"order":30,"rect":{"x":306,"y":955,"width":103,"height":187}},source:require("../../assets/ported/layers/tavernUpstairs/Derived/Consistency/ELD-ENC-TU-031_inserted_image_outlined.png")},
  {...{"id":"ELD-ENC-TU-075","displayName":"Inserted Image - Consistency Outline","hidden":false,"opacity":1.0,"order":31,"rect":{"x":324,"y":1113,"width":178,"height":321}},source:require("../../assets/ported/layers/tavernUpstairs/Derived/Consistency/ELD-ENC-TU-032_inserted_image_outlined.png")},
  {...{"id":"ELD-ENC-TU-076","displayName":"Inserted Image - Consistency Outline","hidden":false,"opacity":1.0,"order":32,"rect":{"x":200,"y":740,"width":332,"height":916}},source:require("../../assets/ported/layers/tavernUpstairs/Derived/Consistency/ELD-ENC-TU-033_inserted_image_outlined.png")},
  {...{"id":"ELD-ENC-TU-077","displayName":"Inserted Image - Consistency Outline","hidden":false,"opacity":1.0,"order":33,"rect":{"x":280,"y":1277,"width":65,"height":164}},source:require("../../assets/ported/layers/tavernUpstairs/Derived/Consistency/ELD-ENC-TU-034_inserted_image_outlined.png")},
  {...{"id":"ELD-ENC-TU-078","displayName":"Inserted Image - Consistency Outline","hidden":false,"opacity":1.0,"order":34,"rect":{"x":267,"y":1136,"width":93,"height":332}},source:require("../../assets/ported/layers/tavernUpstairs/Derived/Consistency/ELD-ENC-TU-035_inserted_image_outlined.png")},
  {...{"id":"ELD-ENC-TU-079","displayName":"Inserted Image - Consistency Outline","hidden":false,"opacity":1.0,"order":35,"rect":{"x":197,"y":766,"width":331,"height":975}},source:require("../../assets/ported/layers/tavernUpstairs/Derived/Consistency/ELD-ENC-TU-036_inserted_image_outlined.png")},
  {...{"id":"ELD-ENC-TU-080","displayName":"Inserted Image - Consistency Outline","hidden":false,"opacity":1.0,"order":36,"rect":{"x":350,"y":932,"width":174,"height":692}},source:require("../../assets/ported/layers/tavernUpstairs/Derived/Consistency/ELD-ENC-TU-037_inserted_image_outlined.png")},
  {...{"id":"ELD-ENC-TU-081","displayName":"Layer 25 - Consistency Outline","hidden":false,"opacity":1.0,"order":37,"rect":{"x":17,"y":474,"width":1412,"height":1165}},source:require("../../assets/ported/layers/tavernUpstairs/Derived/Consistency/ELD-ENC-TU-038_layer_25_outlined.png")},
  {...{"id":"ELD-ENC-TU-082","displayName":"Layer 27 - Consistency Outline","hidden":false,"opacity":1.0,"order":38,"rect":{"x":11,"y":990,"width":1420,"height":980}},source:require("../../assets/ported/layers/tavernUpstairs/Derived/Consistency/ELD-ENC-TU-039_layer_27_outlined.png")},
  {...{"id":"ELD-ENC-TU-083","displayName":"Inserted Image - Consistency Outline","hidden":false,"opacity":1.0,"order":39,"rect":{"x":440,"y":597,"width":962,"height":660}},source:require("../../assets/ported/layers/tavernUpstairs/Derived/Consistency/ELD-ENC-TU-040_inserted_image_outlined.png")},
  {...{"id":"ELD-ENC-TU-084","displayName":"Inserted Image - Consistency Outline","hidden":false,"opacity":1.0,"order":40,"rect":{"x":15,"y":571,"width":1374,"height":898}},source:require("../../assets/ported/layers/tavernUpstairs/Derived/Consistency/ELD-ENC-TU-041_inserted_image_outlined.png")},
  {...{"id":"ELD-ENC-TU-085","displayName":"Layer 29 - Consistency Outline","hidden":false,"opacity":1.0,"order":41,"rect":{"x":55,"y":489,"width":798,"height":484}},source:require("../../assets/ported/layers/tavernUpstairs/Derived/Consistency/ELD-ENC-TU-042_layer_29_outlined.png")},
  {...{"id":"ELD-ENC-TU-086","displayName":"Layer 29 - Consistency Outline","hidden":false,"opacity":1.0,"order":43,"rect":{"x":-10,"y":-10,"width":1460,"height":3140}},source:require("../../assets/ported/layers/tavernUpstairs/Derived/Consistency/ELD-ENC-TU-044_layer_29_outlined.png")},
];
