import type { ArtworkLayer } from './layerAssets';

export const TAVERN_INSIDE_CONSISTENCY_SOURCE_IDS = new Set([
  'ELD-ENC-TI-001',
  'ELD-ENC-TI-002',
  'ELD-ENC-TI-003',
  'ELD-ENC-TI-004',
  'ELD-ENC-TI-005',
  'ELD-ENC-TI-006',
  'ELD-ENC-TI-007',
  'ELD-ENC-TI-008',
  'ELD-ENC-TI-009',
  'ELD-ENC-TI-010',
  'ELD-ENC-TI-011',
  'ELD-ENC-TI-012',
  'ELD-ENC-TI-013',
  'ELD-ENC-TI-014',
  'ELD-ENC-TI-015',
  'ELD-ENC-TI-016',
  'ELD-ENC-TI-017',
  'ELD-ENC-TI-018',
  'ELD-ENC-TI-019',
  'ELD-ENC-TI-020',
  'ELD-ENC-TI-022',
  'ELD-ENC-TI-023',
  'ELD-ENC-TI-024',
  'ELD-ENC-TI-025',
  'ELD-ENC-TI-026',
  'ELD-ENC-TI-027',
  'ELD-ENC-TI-028',
  'ELD-ENC-TI-029',
  'ELD-ENC-TI-030',
  'ELD-ENC-TI-031',
  'ELD-ENC-TI-032',
  'ELD-ENC-TI-033',
  'ELD-ENC-TI-034',
  'ELD-ENC-TI-035',
]);

export const TAVERN_INSIDE_CONSISTENCY_LAYERS: ArtworkLayer[] = [
  {...{"id":"ELD-ENC-TI-038","displayName":"Layer 9 - Consistency Outline","hidden":false,"opacity":1.0,"order":0,"rect":{"x":480,"y":956,"width":318,"height":519}},source:require("../../assets/ported/layers/tavernInside/Derived/Consistency/ELD-ENC-TI-001_layer_9_outlined.png")},
  {...{"id":"ELD-ENC-TI-039","displayName":"Layer 9 - Consistency Outline","hidden":false,"opacity":0.0012401429703459144,"order":1,"rect":{"x":488,"y":950,"width":316,"height":535}},source:require("../../assets/ported/layers/tavernInside/Derived/Consistency/ELD-ENC-TI-002_layer_9_outlined.png")},
  {...{"id":"ELD-ENC-TI-040","displayName":"Layer 10 - Consistency Outline","hidden":false,"opacity":1.0,"order":2,"rect":{"x":596,"y":1417,"width":178,"height":66}},source:require("../../assets/ported/layers/tavernInside/Derived/Consistency/ELD-ENC-TI-003_layer_10_outlined.png")},
  {...{"id":"ELD-ENC-TI-041","displayName":"Human + Huntsman - Consistency Outline","hidden":false,"opacity":1.0,"order":3,"rect":{"x":418,"y":196,"width":372,"height":46}},source:require("../../assets/ported/layers/tavernInside/Derived/Consistency/ELD-ENC-TI-004_human_huntsman_outlined.png")},
  {...{"id":"ELD-ENC-TI-042","displayName":"Karl - Consistency Outline","hidden":false,"opacity":1.0,"order":4,"rect":{"x":418,"y":107,"width":174,"height":82}},source:require("../../assets/ported/layers/tavernInside/Derived/Consistency/ELD-ENC-TI-005_karl_outlined.png")},
  {...{"id":"ELD-ENC-TI-043","displayName":"Lvl 2 - Consistency Outline","hidden":false,"opacity":1.0,"order":5,"rect":{"x":418,"y":271,"width":110,"height":50}},source:require("../../assets/ported/layers/tavernInside/Derived/Consistency/ELD-ENC-TI-006_lvl_2_outlined.png")},
  {...{"id":"ELD-ENC-TI-044","displayName":"XP  0/500 - Consistency Outline","hidden":false,"opacity":1.0,"order":6,"rect":{"x":766,"y":327,"width":182,"height":49}},source:require("../../assets/ported/layers/tavernInside/Derived/Consistency/ELD-ENC-TI-007_xp_0_500_outlined.png")},
  {...{"id":"ELD-ENC-TI-045","displayName":"HP 20 - Consistency Outline","hidden":false,"opacity":1.0,"order":7,"rect":{"x":1064,"y":221,"width":250,"height":78}},source:require("../../assets/ported/layers/tavernInside/Derived/Consistency/ELD-ENC-TI-008_hp_20_outlined.png")},
  {...{"id":"ELD-ENC-TI-046","displayName":"Layer 29 - Consistency Outline","hidden":false,"opacity":1.0,"order":8,"rect":{"x":146,"y":1824,"width":1148,"height":412}},source:require("../../assets/ported/layers/tavernInside/Derived/Consistency/ELD-ENC-TI-009_layer_29_outlined.png")},
  {...{"id":"ELD-ENC-TI-047","displayName":"Inserted Image - Consistency Outline","hidden":false,"opacity":1.0,"order":9,"rect":{"x":979,"y":75,"width":393,"height":370}},source:require("../../assets/ported/layers/tavernInside/Derived/Consistency/ELD-ENC-TI-010_inserted_image_outlined.png")},
  {...{"id":"ELD-ENC-TI-048","displayName":"Layer 19 - Consistency Outline","hidden":false,"opacity":1.0,"order":10,"rect":{"x":88,"y":104,"width":295,"height":302}},source:require("../../assets/ported/layers/tavernInside/Derived/Consistency/ELD-ENC-TI-011_layer_19_outlined.png")},
  {...{"id":"ELD-ENC-TI-049","displayName":"Layer 17 - Consistency Outline","hidden":false,"opacity":1.0,"order":11,"rect":{"x":66,"y":90,"width":350,"height":323}},source:require("../../assets/ported/layers/tavernInside/Derived/Consistency/ELD-ENC-TI-012_layer_17_outlined.png")},
  {...{"id":"ELD-ENC-TI-050","displayName":"Layer 17 - Consistency Outline","hidden":false,"opacity":1.0,"order":12,"rect":{"x":54,"y":79,"width":373,"height":345}},source:require("../../assets/ported/layers/tavernInside/Derived/Consistency/ELD-ENC-TI-013_layer_17_outlined.png")},
  {...{"id":"ELD-ENC-TI-051","displayName":"Layer 21 - Consistency Outline","hidden":false,"opacity":0.7732076644897461,"order":13,"rect":{"x":402,"y":283,"width":375,"height":134}},source:require("../../assets/ported/layers/tavernInside/Derived/Consistency/ELD-ENC-TI-014_layer_21_outlined.png")},
  {...{"id":"ELD-ENC-TI-052","displayName":"Layer 15 - Consistency Outline","hidden":false,"opacity":1.0,"order":14,"rect":{"x":1,"y":24,"width":1449,"height":2630}},source:require("../../assets/ported/layers/tavernInside/Derived/Consistency/ELD-ENC-TI-015_layer_15_outlined.png")},
  {...{"id":"ELD-ENC-TI-053","displayName":"Layer 13 - Consistency Outline","hidden":false,"opacity":1.0,"order":15,"rect":{"x":61,"y":2126,"width":1319,"height":418}},source:require("../../assets/ported/layers/tavernInside/Derived/Consistency/ELD-ENC-TI-016_layer_13_outlined.png")},
  {...{"id":"ELD-ENC-TI-054","displayName":"Layer 27 - Consistency Outline","hidden":false,"opacity":1.0,"order":16,"rect":{"x":87,"y":2293,"width":1258,"height":765}},source:require("../../assets/ported/layers/tavernInside/Derived/Consistency/ELD-ENC-TI-017_layer_27_outlined.png")},
  {...{"id":"ELD-ENC-TI-055","displayName":"Layer 3 - Consistency Outline","hidden":false,"opacity":1.0,"order":17,"rect":{"x":-5,"y":442,"width":1450,"height":2556}},source:require("../../assets/ported/layers/tavernInside/Derived/Consistency/ELD-ENC-TI-018_layer_3_outlined.png")},
  {...{"id":"ELD-ENC-TI-056","displayName":"Inserted Image - Consistency Outline","hidden":false,"opacity":1.0,"order":18,"rect":{"x":34,"y":949,"width":851,"height":641}},source:require("../../assets/ported/layers/tavernInside/Derived/Consistency/ELD-ENC-TI-019_inserted_image_outlined.png")},
  {...{"id":"ELD-ENC-TI-057","displayName":"Inserted Image - Consistency Outline","hidden":false,"opacity":1.0,"order":19,"rect":{"x":840,"y":738,"width":562,"height":851}},source:require("../../assets/ported/layers/tavernInside/Derived/Consistency/ELD-ENC-TI-020_inserted_image_outlined.png")},
  {...{"id":"ELD-ENC-TI-058","displayName":"Inserted Image - Consistency Outline","hidden":false,"opacity":1.0,"order":21,"rect":{"x":33,"y":605,"width":1324,"height":920}},source:require("../../assets/ported/layers/tavernInside/Derived/Consistency/ELD-ENC-TI-022_inserted_image_outlined.png")},
  {...{"id":"ELD-ENC-TI-059","displayName":"Inserted Image - Consistency Outline","hidden":false,"opacity":1.0,"order":22,"rect":{"x":-10,"y":499,"width":1448,"height":980}},source:require("../../assets/ported/layers/tavernInside/Derived/Consistency/ELD-ENC-TI-023_inserted_image_outlined.png")},
  {...{"id":"ELD-ENC-TI-060","displayName":"Inserted Image - Consistency Outline","hidden":false,"opacity":1.0,"order":23,"rect":{"x":594,"y":478,"width":460,"height":305}},source:require("../../assets/ported/layers/tavernInside/Derived/Consistency/ELD-ENC-TI-024_inserted_image_outlined.png")},
  {...{"id":"ELD-ENC-TI-061","displayName":"Inserted Image - Consistency Outline","hidden":false,"opacity":1.0,"order":24,"rect":{"x":265,"y":768,"width":1102,"height":700}},source:require("../../assets/ported/layers/tavernInside/Derived/Consistency/ELD-ENC-TI-025_inserted_image_outlined.png")},
  {...{"id":"ELD-ENC-TI-062","displayName":"Inserted Image - Consistency Outline","hidden":false,"opacity":1.0,"order":25,"rect":{"x":-10,"y":460,"width":1460,"height":1100}},source:require("../../assets/ported/layers/tavernInside/Derived/Consistency/ELD-ENC-TI-026_inserted_image_outlined.png")},
  {...{"id":"ELD-ENC-TI-063","displayName":"Inserted Image - Consistency Outline","hidden":false,"opacity":1.0,"order":26,"rect":{"x":304,"y":818,"width":435,"height":488}},source:require("../../assets/ported/layers/tavernInside/Derived/Consistency/ELD-ENC-TI-027_inserted_image_outlined.png")},
  {...{"id":"ELD-ENC-TI-064","displayName":"Inserted Image - Consistency Outline","hidden":false,"opacity":1.0,"order":27,"rect":{"x":407,"y":747,"width":515,"height":482}},source:require("../../assets/ported/layers/tavernInside/Derived/Consistency/ELD-ENC-TI-028_inserted_image_outlined.png")},
  {...{"id":"ELD-ENC-TI-065","displayName":"Inserted Image - Consistency Outline","hidden":false,"opacity":1.0,"order":28,"rect":{"x":2,"y":482,"width":1411,"height":1109}},source:require("../../assets/ported/layers/tavernInside/Derived/Consistency/ELD-ENC-TI-029_inserted_image_outlined.png")},
  {...{"id":"ELD-ENC-TI-066","displayName":"Layer 31 - Consistency Outline","hidden":false,"opacity":1.0,"order":29,"rect":{"x":26,"y":686,"width":1377,"height":900}},source:require("../../assets/ported/layers/tavernInside/Derived/Consistency/ELD-ENC-TI-030_layer_31_outlined.png")},
  {...{"id":"ELD-ENC-TI-067","displayName":"Layer 25 - Consistency Outline","hidden":false,"opacity":1.0,"order":30,"rect":{"x":17,"y":474,"width":1412,"height":1165}},source:require("../../assets/ported/layers/tavernInside/Derived/Consistency/ELD-ENC-TI-031_layer_25_outlined.png")},
  {...{"id":"ELD-ENC-TI-068","displayName":"Layer 27 - Consistency Outline","hidden":false,"opacity":1.0,"order":31,"rect":{"x":11,"y":990,"width":1420,"height":980}},source:require("../../assets/ported/layers/tavernInside/Derived/Consistency/ELD-ENC-TI-032_layer_27_outlined.png")},
  {...{"id":"ELD-ENC-TI-069","displayName":"Inserted Image - Consistency Outline","hidden":false,"opacity":1.0,"order":32,"rect":{"x":440,"y":597,"width":962,"height":660}},source:require("../../assets/ported/layers/tavernInside/Derived/Consistency/ELD-ENC-TI-033_inserted_image_outlined.png")},
  {...{"id":"ELD-ENC-TI-070","displayName":"Inserted Image - Consistency Outline","hidden":false,"opacity":1.0,"order":33,"rect":{"x":15,"y":571,"width":1374,"height":898}},source:require("../../assets/ported/layers/tavernInside/Derived/Consistency/ELD-ENC-TI-034_inserted_image_outlined.png")},
  {...{"id":"ELD-ENC-TI-071","displayName":"Layer 29 - Consistency Outline","hidden":false,"opacity":1.0,"order":34,"rect":{"x":55,"y":489,"width":798,"height":484}},source:require("../../assets/ported/layers/tavernInside/Derived/Consistency/ELD-ENC-TI-035_layer_29_outlined.png")},
];
