from __future__ import annotations

import json
import sys
import tempfile
from pathlib import Path

from PIL import Image

from extractProcreateLayers import extract


SOURCE_LAYER_FOR_RESULT = {result: 28 - result for result in range(1, 21)}
LANDING_RECT = (547, 1720, 866, 2000)


def import_dice(source: Path, output: Path, module: Path) -> None:
    output.mkdir(parents=True, exist_ok=True)
    with tempfile.TemporaryDirectory(prefix="eldra-dice20-") as temp_name:
        temp = Path(temp_name)
        extract(source, temp, set(SOURCE_LAYER_FOR_RESULT.values()))
        for result, layer_index in SOURCE_LAYER_FOR_RESULT.items():
            with Image.open(temp / f"{layer_index:02d}.png") as layer:
                layer.crop(LANDING_RECT).save(output / f"roll-{result:02d}.png")

    manifest = {
        "schema": "eldra.dice20.v1",
        "source": source.name,
        "canvas": {"width": 1440, "height": 3120},
        "landingRect": {
            "x": LANDING_RECT[0],
            "y": LANDING_RECT[1],
            "width": LANDING_RECT[2] - LANDING_RECT[0],
            "height": LANDING_RECT[3] - LANDING_RECT[1],
        },
        "results": [
            {"result": result, "sourceLayer": SOURCE_LAYER_FOR_RESULT[result], "file": f"roll-{result:02d}.png"}
            for result in range(1, 21)
        ],
    }
    (output / "AssetManifest.json").write_text(json.dumps(manifest, indent=2), encoding="utf-8")

    requires = ",\n  ".join(
        f'require("../../assets/ported/game/dice20/roll-{result:02d}.png")' for result in range(1, 21)
    )
    module.parent.mkdir(parents=True, exist_ok=True)
    module.write_text(
        "// Generated by scripts/importDice20.py.\n"
        "export const DICE_20_CANVAS = { width: 1440, height: 3120 } as const;\n"
        "export const DICE_20_LANDING_RECT = { x: 547, y: 1720, width: 319, height: 280 } as const;\n"
        f"export const DICE_20_RESULTS = [\n  {requires}\n] as const;\n",
        encoding="utf-8",
    )


if __name__ == "__main__":
    if len(sys.argv) != 4:
        raise SystemExit("Usage: importDice20.py <source.procreate> <output-dir> <module.ts>")
    import_dice(Path(sys.argv[1]), Path(sys.argv[2]), Path(sys.argv[3]))
