from __future__ import annotations

import json
import plistlib
import sys
import zipfile
from pathlib import Path

from PIL import Image

from extractProcreateComposite import decode_tile, uid_value


INVENTORY_INDICES = set(range(0, 28)) | {41}
EQUIPMENT_INDICES = set(range(28, 41))


def read_layer(archive: zipfile.ZipFile, uuid: str, width: int, height: int) -> Image.Image:
    canvas = Image.new("RGBA", (width, height))
    for entry in archive.infolist():
        if not (entry.filename.startswith(f"{uuid}/") and entry.filename.endswith(".lz4")):
            continue
        tile_x, tile_y = [int(value) for value in Path(entry.filename).stem.split("~")]
        tile_width = min(256, width - tile_x * 256)
        tile_height = min(256, height - tile_y * 256)
        tile = Image.frombytes(
            "RGBA", (tile_width, tile_height), decode_tile(archive.read(entry)), "raw", "RGBA"
        ).transpose(Image.Transpose.FLIP_TOP_BOTTOM)
        canvas.alpha_composite(tile, (tile_x * 256, height - tile_y * 256 - tile_height))
    return canvas


def compose(layers: dict[int, tuple[Image.Image, float]], selected: set[int], width: int, height: int):
    result = Image.new("RGBA", (width, height))
    for index in sorted(selected, reverse=True):
        item = layers.get(index)
        if not item:
            continue
        image, opacity = item
        if opacity < 1:
            image = image.copy()
            image.putalpha(image.getchannel("A").point(lambda value: int(value * opacity)))
        result.alpha_composite(image)
    bbox = result.getbbox()
    if bbox is None:
        raise RuntimeError("Selected layers produced an empty image")
    return result.crop(bbox), bbox


def import_document(source: Path, asset_root: Path, module_path: Path) -> None:
    asset_root.mkdir(parents=True, exist_ok=True)
    with zipfile.ZipFile(source) as archive:
        document = plistlib.loads(archive.read("Document.archive"))
        objects = document["$objects"]
        root = uid_value(objects, document["$top"]["root"])
        width, height = [int(value) for value in uid_value(objects, root["size"]).strip("{}").split(",")]
        source_layers = uid_value(objects, root["layers"])["NS.objects"]
        layers: dict[int, tuple[Image.Image, float]] = {}
        records = []
        for index, layer_uid in enumerate(source_layers):
            if index not in INVENTORY_INDICES | EQUIPMENT_INDICES:
                continue
            layer = uid_value(objects, layer_uid)
            if bool(layer.get("hidden", False)):
                continue
            uuid = uid_value(objects, layer["UUID"])
            image = read_layer(archive, uuid, width, height)
            if image.getbbox() is None:
                continue
            opacity = float(layer.get("opacity", 1.0))
            name = str(uid_value(objects, layer["name"])) if "name" in layer else f"Text {index + 1}"
            layers[index] = (image, opacity)
            records.append({"id": f"ELD-IE12-{index + 1:03d}", "name": name, "order": index})

    inventory, inventory_bbox = compose(layers, INVENTORY_INDICES, width, height)
    equipment, equipment_bbox = compose(layers, EQUIPMENT_INDICES, width, height)
    inventory_file = "ELD-IE12-Inventory.png"
    equipment_file = "ELD-IE12-Equipment.png"
    inventory.save(asset_root / inventory_file, optimize=True)
    equipment.save(asset_root / equipment_file, optimize=True)
    manifest = {
        "schema": "eldra.inventory-equipment.v1",
        "source": source.name,
        "canvas": {"width": width, "height": height},
        "inventory": {"file": inventory_file, "bbox": inventory_bbox},
        "equipment": {"file": equipment_file, "bbox": equipment_bbox},
        "layers": records,
    }
    (asset_root / "AssetManifest.json").write_text(json.dumps(manifest, indent=2), encoding="utf-8")
    module = f'''// Generated by scripts/importInventoryEquipment12.py.
export const INVENTORY_EQUIPMENT_12_CANVAS = {{ width: {width}, height: {height} }} as const;
export const INVENTORY_BOARD = {{ source: require("../../assets/ported/menu/inventoryEquipment12/{inventory_file}"), rect: {{ x: {inventory_bbox[0]}, y: {inventory_bbox[1]}, width: {inventory_bbox[2] - inventory_bbox[0]}, height: {inventory_bbox[3] - inventory_bbox[1]} }} }} as const;
export const EQUIPMENT_BOARD = {{ source: require("../../assets/ported/menu/inventoryEquipment12/{equipment_file}"), rect: {{ x: {equipment_bbox[0]}, y: {equipment_bbox[1]}, width: {equipment_bbox[2] - equipment_bbox[0]}, height: {equipment_bbox[3] - equipment_bbox[1]} }} }} as const;
'''
    module_path.write_text(module, encoding="utf-8")
    print(f"Inventory {inventory_bbox}; equipment {equipment_bbox}; {len(records)} source layers.")


if __name__ == "__main__":
    if len(sys.argv) != 4:
        raise SystemExit("Usage: importInventoryEquipment12.py <source.procreate> <asset-output> <typescript-output>")
    import_document(Path(sys.argv[1]), Path(sys.argv[2]), Path(sys.argv[3]))
