from __future__ import annotations

import json
import plistlib
import sys
import zipfile
from pathlib import Path

from PIL import Image, ImageChops, ImageFilter

from extractProcreateComposite import decode_tile, uid_value


CANVAS_FILE = "ELD-FV10-Forest-Valley.png"
OUTLINE = (247, 231, 202, 235)
OUTLINE_RADIUS = 5


def read_layer(archive: zipfile.ZipFile, uuid: str, width: int, height: int) -> Image.Image:
    canvas = Image.new("RGBA", (width, height))
    for entry in archive.infolist():
        if not (entry.filename.startswith(f"{uuid}/") and entry.filename.endswith(".lz4")):
            continue
        tile_x, tile_y = [int(value) for value in Path(entry.filename).stem.split("~")]
        tile_width = min(256, width - tile_x * 256)
        tile_height = min(256, height - tile_y * 256)
        tile = Image.frombytes(
            "RGBA", (tile_width, tile_height), decode_tile(archive.read(entry)), "raw", "RGBA"
        ).transpose(Image.Transpose.FLIP_TOP_BOTTOM)
        canvas.alpha_composite(tile, (tile_x * 256, height - tile_y * 256 - tile_height))
    return canvas


def outlined(image: Image.Image) -> Image.Image:
    margin = OUTLINE_RADIUS + 1
    padded = Image.new("RGBA", (image.width + margin * 2, image.height + margin * 2))
    padded.alpha_composite(image, (margin, margin))
    alpha = padded.getchannel("A")
    grown = alpha.filter(ImageFilter.MaxFilter(OUTLINE_RADIUS * 2 + 1))
    edge = ImageChops.subtract(grown, alpha).point(lambda value: value * OUTLINE[3] // 255)
    backing = Image.new("RGBA", padded.size, OUTLINE[:3] + (0,))
    backing.putalpha(edge)
    backing.alpha_composite(padded)
    return backing


def import_document(source: Path, asset_root: Path, module_path: Path) -> None:
    asset_root.mkdir(parents=True, exist_ok=True)
    with zipfile.ZipFile(source) as archive:
        document = plistlib.loads(archive.read("Document.archive"))
        objects = document["$objects"]
        root = uid_value(objects, document["$top"]["root"])
        width, height = [int(value) for value in uid_value(objects, root["size"]).strip("{}").split(",")]
        layers = uid_value(objects, root["layers"])["NS.objects"]
        composite = Image.new("RGBA", (width, height))
        records = []

        # Procreate stores its topmost layer first; build the scene from bottom to top.
        for index in reversed(range(len(layers))):
            layer = uid_value(objects, layers[index])
            if bool(layer.get("hidden", False)):
                continue
            name = str(uid_value(objects, layer["name"])) if "name" in layer else f"Text {index + 1}"
            uuid = uid_value(objects, layer["UUID"])
            canvas = read_layer(archive, uuid, width, height)
            bbox = canvas.getbbox()
            if not bbox:
                continue
            left, top, right, bottom = bbox
            image = outlined(canvas.crop(bbox))
            x, y = left - OUTLINE_RADIUS - 1, top - OUTLINE_RADIUS - 1
            opacity = float(layer.get("opacity", 1.0))
            if opacity < 1:
                image.putalpha(image.getchannel("A").point(lambda value: int(value * opacity)))
            asset_id = f"ELD-FV10-{index + 1:03d}"
            filename = f"{asset_id}.png"
            image.save(asset_root / filename, optimize=True)
            composite.alpha_composite(image, (x, y))
            records.append({
                "id": asset_id,
                "name": name,
                "order": index,
                "opacity": opacity,
                "rect": {"x": x, "y": y, "width": image.width, "height": image.height},
                "file": filename,
                "outline": {"color": "#F7E7CA", "radius": OUTLINE_RADIUS},
            })

    composite.save(asset_root / CANVAS_FILE, optimize=True)
    manifest = {
        "schema": "eldra.gameplay-scene.v1",
        "source": source.name,
        "canvas": {"width": width, "height": height},
        "composite": CANVAS_FILE,
        "layers": records,
    }
    (asset_root / "AssetManifest.json").write_text(json.dumps(manifest, indent=2), encoding="utf-8")
    lines = [
        "// Generated by scripts/importForestValley10.py; individual outlined layers remain available.",
        "export type ForestValley10Layer = { id: string; name: string; order: number; opacity: number; rect: { x: number; y: number; width: number; height: number }; source: number };",
        f"export const FOREST_VALLEY_10_CANVAS = {{ width: {width}, height: {height} }} as const;",
        f'export const FOREST_VALLEY_10_COMPOSITE = require("../../assets/ported/layers/forestValley10/{CANVAS_FILE}");',
        "export const FOREST_VALLEY_10_LAYERS: ForestValley10Layer[] = [",
    ]
    for record in records:
        metadata = {key: value for key, value in record.items() if key not in ("file", "outline")}
        lines.append(f'  {{...{json.dumps(metadata, separators=(",", ":"))},source:require("../../assets/ported/layers/forestValley10/{record["file"]}")}},')
    lines.extend(["];", ""])
    module_path.write_text("\n".join(lines), encoding="utf-8")
    print(f"Imported {len(records)} visible layers at {width}x{height}.")


if __name__ == "__main__":
    if len(sys.argv) != 4:
        raise SystemExit("Usage: importForestValley10.py <source.procreate> <asset-output> <typescript-output>")
    import_document(Path(sys.argv[1]), Path(sys.argv[2]), Path(sys.argv[3]))
